name: 'Convert Markdown to PDF'
description: 'Github action that generates a PDF file from a Markdown file.'
author: 'André Rocco'

inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'