name: Markdown to PDF conversion

on:
    push:
        branches: [main]

jobs:
    markdown-to-pdf:
        runs-on: ubuntu-latest

        name: Convert Markdown to PDF
        steps:
            # To use this repository's private action,
            # you must check out the repository
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Markdown to PDF
              uses: ./ # Uses an action in the root directory
              # TODO - Replace with andre-rocco/markdown-to-pdf@v1 when published to the marketplace
              id: markdown-to-pdf
              with:
                  markdown_path: 'README.md'
                  output_dir: 'output'
                  output_filename: 'README.pdf'
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set-up Node.js
#     uses: actions/setup-node@v3
#     with:
#       node-version: '18'

#     - name: Runs
